### ISSUE TITLE
Página do NodeJs não está funcionando.

### ISSUE THREAD

**Issue by drdaniloteixeira** [flaviomicheletti/devfuria.com.br#122]
http://devfuria.com.br/node.js/

404

File not found

abs

**Comment by flaviomicheletti** [comment]
Boa man, obrigado por ter avisado !
Chegando em casa, vejo o que aconteceu.

**Comment by drdaniloteixeira** [comment]
> Flaviom


obrigado pela ajuda...

tenho aprendido / estudado programação pelo devfuria

obrigado pelo projeto!
Que Deus continue te abençoando!

**Comment by flaviomicheletti** [comment]
Que legal Danilo !!!
Fico feliz pra caramba !
Você está em qual ano da faculdade ?
Já está trabalhando ?
Qual linguagem escolheu para estudar ?

Tenta este link aqui http://devfuria.com.br/nodejs/

**Comment by drdaniloteixeira** [comment]
Não faço faculdade não rsrsrs....

Sou empresário.

Mas sempre amei ti...

Desde quando era criança, em 97, 98, eu mexia em computador internet, IRC...

Até, na época programei um pouco em IRC Scripting, mas na época o
conhecimento era escasso né...

Aprendi fuçando, mexendo nas coisas...

Sempre quis aprender a programar, porém não pude priorizar isso anos
atrás...

To aprendendo web... nodejs..

e você?


abs

**Comment by flaviomicheletti** [comment]
Danilo, eu atuo como desenvolvedor desde 2007.
Já passei por linguagens como APS, PHP, Python, Java  e Node(JavaScript).

Vc está pensando em desenvolvedor algo para sua empresa ?
