### ISSUE TITLE
Curso Lógica de Programação + TDD

### ISSUE THREAD

**Issue by cami-la** [flaviomicheletti/devfuria.com.br#123]
Olá, amigo!
Gostaria de saber se tem alguma turma aberta para o curso de Curso Lógica de Programação + TDD. 
Procurei no site e no canal do Youtube e não achei nada atualizado sobre.

**Comment by flaviomicheletti** [comment]
Olá Camila, tudo bem ?
Eu encerrei as turmas pois estou reciclando o curso.
Mas eu posso disponibilizar o curso para você, sem problemas.
Me envia seu email ou whats que eu passo os acessos por lá.
sitedevfuria@gmail.com.br

**Comment by cami-la** [comment]
Bom dia, tudo certo por aqui. :)
Te respondi por e-mail mas acho que você ainda não viu!

Sim, deixa eu te explicar.  Como falei no e-mail...
Estou aprendendo POO com Python em um curso livre e travei na parte de TDD.

Agora estou aprendendo POO em Java, porque olhando a grade curricular da minha facul, vou estudar POO em Java. Aí pra adiantar e fazer com que esse assunto de POO entre na minha cabeça já estou adiantando.

Vi que você tem esse curso de Lógica de programação + TDD, então acredito que irá me ajudar bastante a fixar bem o conceito de TDD. 

E desde já obrigada mesmo por me responder. 

camiladsantoscavalcante@gmail.com
81 98769-3928 whatsApp Camila.
81 99513-7658 Telegram Camila.

**Comment by flaviomicheletti** [comment]
Oi Camila, vacilei, passei email errado.

Me encaminho o seu email anterior, pode ser ?

sitedevfuria@gmail.com

É sem "br"
