### ISSUE TITLE
Link quebrado (http://devfuria.com.br/o-que-e-tdd/)

### ISSUE THREAD

**Issue by guyrux** [flaviomicheletti/devfuria.com.br#126]
Eu estava navegando na página http://devfuria.com.br/tdd/ e o link para o artigo [Uma breve noção sobre o que é TDD](http://devfuria.com.br/o-que-e-tdd/) está quebrado.

Aproveito para agradecer o conteúdo.

Grande abraço.

**Comment by flaviomicheletti** [comment]
Obrigado fera!

http://devfuria.com.br/tdd/o-que-e-tdd/

**Comment by flaviomicheletti** [comment]
https://github.com/flaviomicheletti/tdd/commit/ea5a43b6c860c201f059a771682b857214734c0a
